name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: gemfiles/activesupport_${{ matrix.activesupport_version }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1", ruby-head]
        activesupport_version: [2.3_LTS, 5, 6, 7]
        include:
          - ruby: "2.6"
            activesupport_version: 3 
          - ruby: "2.6"
            activesupport_version: 4
        exclude:
          - ruby: "2.6"
            activesupport_version: 7 
          - ruby: ruby-head
            activesupport_version: 2.3_LTS
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # 'bundle install' and cache gems
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: bundle exec rspec
